# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-submodules:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Check all commits in git submodules available
      run: git submodule init && git submodule update --recursive --remote

    - name: Check all submodules up-to-date
      run: git diff --exit-code

    - name: Check master points to main
      run: |
        for s in ./submodules/*/ ; do
          pushd "$s"
          git diff origin/master --exit-code || echo "Broker Master in $s"
          popd > /dev/null
        done

  check-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check all URLs
      run: ./scripts/check_all_urls.sh

    - name: Check existing swagger specification is up-to-date
      run: curl https://api.aspose.cloud/v3.0/barcode/swagger/spec | diff --strip-trailing-cr -y --suppress-common-lines spec/aspose-barcode-cloud.json -
