name: Check pull request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-submodules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check all submodules up-to-date
        run: |
          git submodule update --recursive --remote
          git diff --exit-code

  check-swagger:
    runs-on: ubuntu-latest
    needs: [check-submodules]
    steps:
      - uses: actions/checkout@v4
      - name: Check existing swagger specification is up-to-date
        run: curl https://api.aspose.cloud/v4.0/barcode/swagger/spec | diff --strip-trailing-cr -y --suppress-common-lines spec/aspose-barcode-cloud.json -
